name: environment
channels:
    - conda-forge
    - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    - defaults
dependencies:
    - python=3
    - pip=19.2.1
    - jupyter
    - notebook
    - xeus-cling=0.7.1
    - pip:
        - jupyter-c-kernel==1.2.2
